fix(logging): handling exceptions, state what to expect, and log it.
there's a bit too many naked `except:` clauses, plus many more that do
not log anything just swallowing the exception silently.  I'm trying
to reduce that.

one "catch-all" clause in bauble/editor.py:1760 is silencing a
TypeError: attribute name must be string, not 'NoneType'
I've added a logger.warning, but kept the exception swallowed.